# Generated by Django 5.2 on 2025-05-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date_creation',
            field=models.DateTimeField(),
        ),
    ]
